locale: 'pt'

backend:
  name: git-gateway
  branch: master

display_url: https://benditocheiro.art
logo_url: https://raw.githubusercontent.com/saulofilho/benditocheiro/master/static/assets/logos/logo.png

media_folder: static/assets
public_folder: /assets

collections:
  - name: produto
    label: Produtos
    folder: _data/produto
    slug: '{{slug}}'
    create: true
    editor:
      preview: false
    fields:
      - {
          name: template,
          label: Template,
          widget: hidden,
          default: ProdutoPost,
        }
      - { name: date, label: Data, widget: datetime, dateFormat: "DD.MM.YYYY", required: false }
      - { name: title, label: Nome do Produto, widget: string, required: false }
      - label: Categoria do Produto
        name: categoria_produto
        widget: list
        max: 1
        required: false
        fields:
          - label: Categoria
            name: categoria_list
            widget: relation
            collection: categorias
            search_fields: ['title']
            value_field: 'title'
      - { name: img, label: Imagem do Produto, widget: image, required: false }
      - { name: body, label: Texto sobre o Produto, widget: markdown, required: false }
      - { name: preco, label: Preço do Produto, widget: string, required: false }
      - label: Imagens do Produto
        name: img_produto
        widget: list
        required: false
        fields:
          - label: Imagens do Produto
            name: img_list
            widget: image
            choose_url: false
            media_library:
              config:
                multiple: false
  - name: categorias
    label: Categoria de Produto
    editor:
      preview: false
    folder: _data/categoria
    slug: '{{slug}}'
    create: true
    fields:
      - { label: Nome da Categoria, name: title, widget: string }
